'use client';

import { useApp } from '@/lib/store';
import { useState, useCallback } from 'react';
import { ClipboardList, CheckCircle2, Download, StickyNote, Plus, X, Trash2 } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import type { ActionPlan, UserNote } from '@/types/document';
import { v4Style } from '@/lib/documents/utils';

export function ActionsTab() {
  const { state, dispatch } = useApp();
  const [isLoadingPlan, setIsLoadingPlan] = useState(false);
  const [isLoadingBrief, setIsLoadingBrief] = useState(false);
  const [newNote, setNewNote] = useState('');
  const [showNoteInput, setShowNoteInput] = useState(false);

  const generateActionPlan = useCallback(async () => {
    if (!state.document || !state.analysis) return;
    setIsLoadingPlan(true);
    try {
      const res = await fetch('/api/action-plan', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ document: state.document, analysis: state.analysis }),
      });
      if (!res.ok) throw new Error('Failed');
      const data = await res.json();
      dispatch({ type: 'SET_ACTION_PLAN', payload: data.actionPlan });
    } catch {
      // Use analysis-derived fallback
    } finally {
      setIsLoadingPlan(false);
    }
  }, [state.document, state.analysis, dispatch]);

  const generateBrief = useCallback(async () => {
    if (!state.document || !state.analysis) return;
    setIsLoadingBrief(true);
    try {
      const res = await fetch('/api/lawyer-brief', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          document: state.document,
          analysis: state.analysis,
          userNotes: state.notes.map(n => n.text),
        }),
      });
      if (!res.ok) throw new Error('Failed');
      const data = await res.json();
      dispatch({ type: 'SET_LAWYER_BRIEF', payload: data.brief });
    } catch {
      // Error handled
    } finally {
      setIsLoadingBrief(false);
    }
  }, [state.document, state.analysis, state.notes, dispatch]);

  const addNote = () => {
    if (!newNote.trim() || !state.document) return;
    const note: UserNote = {
      id: `note-${v4Style()}`,
      documentId: state.document.id,
      text: newNote.trim(),
      type: 'note',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
    dispatch({ type: 'ADD_NOTE', payload: note });
    setNewNote('');
    setShowNoteInput(false);
  };

  const exportBrief = () => {
    if (!state.lawyerBrief) return;
    const brief = state.lawyerBrief;
    const text = `LEGAL REVIEW BRIEF
Generated by LEXORA — ${new Date(brief.generatedAt).toLocaleDateString()}

OVERVIEW
${brief.overview}

PARTIES
${brief.parties.join('\n')}

PURPOSE
${brief.purpose}

IMPORTANT OBLIGATIONS
${brief.importantObligations.map(o => `• ${o}`).join('\n')}

KEY DATES
${brief.keyDates.map(d => `• ${d}`).join('\n')}

MONETARY TERMS
${brief.monetaryTerms.map(m => `• ${m}`).join('\n')}

ATTENTION AREAS
${brief.attentionAreas.map(a => `• ${a}`).join('\n')}

AMBIGUITIES
${brief.ambiguities.map(a => `• ${a}`).join('\n')}

KEY QUESTIONS
${brief.keyQuestions.map(q => `• ${q}`).join('\n')}

SECTIONS REQUIRING REVIEW
${brief.sectionsRequiringReview.map(s => `• ${s}`).join('\n')}

${brief.userNotes.length > 0 ? `USER NOTES\n${brief.userNotes.map(n => `• ${n}`).join('\n')}` : ''}

---
DISCLAIMER: This brief was generated by LEXORA, an AI-powered document analysis tool. It is not legal advice. Important decisions should be reviewed with a qualified legal professional.`;

    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Legal_Review_Brief_${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="p-4 space-y-6">
      {/* Action Plan */}
      <div>
        <div className="flex items-center justify-between mb-3">
          <h3 className="text-[10px] font-semibold text-lexora-500 uppercase tracking-wider flex items-center gap-1">
            <ClipboardList className="w-3 h-3" /> Your Action Plan
          </h3>
          {!state.actionPlan && (
            <button
              onClick={generateActionPlan}
              disabled={isLoadingPlan}
              className="text-[10px] font-medium text-accent-500 hover:text-accent-400 transition-colors disabled:opacity-50"
            >
              {isLoadingPlan ? 'Generating...' : 'Generate plan'}
            </button>
          )}
        </div>

        {state.actionPlan ? (
          <div className="space-y-4">
            {/* Before signing */}
            <div>
              <div className="text-[10px] font-semibold text-lexora-400 mb-2">Before Signing</div>
              <div className="space-y-1">
                {state.actionPlan.beforeSigning.map(item => (
                  <label key={item.id} className="flex items-start gap-2 p-2 rounded hover:bg-lexora-800/30 cursor-pointer">
                    <input type="checkbox" className="mt-0.5 accent-accent-500" />
                    <span className="text-[11px] text-lexora-300">{item.text}</span>
                    {item.priority === 'high' && <span className="risk-badge risk-badge--high shrink-0">priority</span>}
                  </label>
                ))}
              </div>
            </div>

            {/* After signing */}
            <div>
              <div className="text-[10px] font-semibold text-lexora-400 mb-2">After Signing</div>
              <div className="space-y-1">
                {state.actionPlan.afterSigning.map(item => (
                  <label key={item.id} className="flex items-start gap-2 p-2 rounded hover:bg-lexora-800/30 cursor-pointer">
                    <input type="checkbox" className="mt-0.5 accent-accent-500" />
                    <span className="text-[11px] text-lexora-300">{item.text}</span>
                  </label>
                ))}
              </div>
            </div>

            {/* Questions for counsel */}
            <div>
              <div className="text-[10px] font-semibold text-lexora-400 mb-2">Questions for Counsel</div>
              {state.actionPlan.questionsForCounsel.map((q, i) => (
                <p key={i} className="text-[11px] text-lexora-300 pl-3 border-l-2 border-accent-500/30 mb-2">{q}</p>
              ))}
            </div>
          </div>
        ) : !isLoadingPlan ? (
          <p className="text-xs text-lexora-500">Generate an action plan to see personalized next steps.</p>
        ) : (
          <div className="space-y-2">
            {[1, 2, 3].map(i => <div key={i} className="skeleton h-8 w-full" />)}
          </div>
        )}
      </div>

      {/* Lawyer Brief */}
      <div>
        <div className="flex items-center justify-between mb-3">
          <h3 className="text-[10px] font-semibold text-lexora-500 uppercase tracking-wider flex items-center gap-1">
            <Download className="w-3 h-3" /> Legal Review Brief
          </h3>
          <div className="flex gap-2">
            {state.lawyerBrief && (
              <button
                onClick={exportBrief}
                className="text-[10px] font-medium text-accent-500 hover:text-accent-400 transition-colors flex items-center gap-1"
              >
                <Download className="w-3 h-3" /> Export
              </button>
            )}
            <button
              onClick={generateBrief}
              disabled={isLoadingBrief}
              className="text-[10px] font-medium text-accent-500 hover:text-accent-400 transition-colors disabled:opacity-50"
            >
              {isLoadingBrief ? 'Generating...' : state.lawyerBrief ? 'Regenerate' : 'Generate brief'}
            </button>
          </div>
        </div>

        {state.lawyerBrief ? (
          <div className="p-3 rounded-lg border border-lexora-800 bg-lexora-900/30 space-y-2">
            <p className="text-xs text-lexora-300">{state.lawyerBrief.overview}</p>
            <div className="text-[10px] text-success flex items-center gap-1">
              <CheckCircle2 className="w-3 h-3" /> Brief ready for export
            </div>
          </div>
        ) : (
          <p className="text-xs text-lexora-500">Generate a concise summary ready for a lawyer consultation.</p>
        )}
      </div>

      {/* Notes */}
      <div>
        <div className="flex items-center justify-between mb-3">
          <h3 className="text-[10px] font-semibold text-lexora-500 uppercase tracking-wider flex items-center gap-1">
            <StickyNote className="w-3 h-3" /> Personal Notes
          </h3>
          <button
            onClick={() => setShowNoteInput(!showNoteInput)}
            className="text-[10px] font-medium text-accent-500 hover:text-accent-400 transition-colors"
          >
            <Plus className="w-3 h-3" />
          </button>
        </div>

        <AnimatePresence>
          {showNoteInput && (
            <motion.div
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: 'auto' }}
              exit={{ opacity: 0, height: 0 }}
              className="mb-3"
            >
              <div className="flex gap-2">
                <input
                  type="text"
                  value={newNote}
                  onChange={(e) => setNewNote(e.target.value)}
                  onKeyDown={(e) => { if (e.key === 'Enter') addNote(); }}
                  placeholder="Add a note or question..."
                  className="flex-1 px-3 py-1.5 rounded-md bg-lexora-900 border border-lexora-800 text-xs text-lexora-200 placeholder:text-lexora-600 focus:border-accent-500/50 focus:outline-none"
                  aria-label="Add a personal note"
                />
                <button onClick={addNote} className="px-3 py-1.5 rounded-md bg-accent-600 text-white text-xs hover:bg-accent-500">Add</button>
              </div>
              <p className="text-[10px] text-lexora-600 mt-1">Notes stay local and are not sent to AI unless you choose.</p>
            </motion.div>
          )}
        </AnimatePresence>

        <div className="space-y-1.5">
          {state.notes.map(note => (
            <div key={note.id} className="flex items-start gap-2 p-2 rounded border border-lexora-800 bg-lexora-900/30 group">
              <StickyNote className="w-3 h-3 text-accent-500 mt-0.5 shrink-0" />
              <span className="text-[11px] text-lexora-300 flex-1">{note.text}</span>
              <button
                onClick={() => dispatch({ type: 'REMOVE_NOTE', payload: note.id })}
                className="opacity-0 group-hover:opacity-100 transition-opacity"
                aria-label="Remove note"
              >
                <Trash2 className="w-3 h-3 text-lexora-600 hover:text-danger" />
              </button>
            </div>
          ))}
          {state.notes.length === 0 && !showNoteInput && (
            <p className="text-xs text-lexora-600">No notes yet. Add questions or reminders for yourself.</p>
          )}
        </div>
      </div>
    </div>
  );
}
